/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Objetos.Semestre;
import Objetos.Materia;
import Conexion.Conexiones;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PARRA
 */
public class vtnPrincipal extends javax.swing.JFrame {

    public static PreparedStatement ps = null;
    public static ResultSet rs;
    public static Connection con = Conexiones.conectar();
    public static DefaultTableModel modelo = new DefaultTableModel();

    public vtnPrincipal() {
        initComponents();
        lbienvenido.setText(lbienvenido + vtnLogin.usuario);
        jtabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpusuario = new javax.swing.JPanel();
        lbienvenido = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnaltasemestre = new javax.swing.JButton();
        btnaltamateria = new javax.swing.JButton();
        btnaltareticula = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        btnnuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jctipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbienvenido.setText("Bienvenido ");

        btnaltasemestre.setText("Nuevo Semestre");
        btnaltasemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaltasemestreActionPerformed(evt);
            }
        });

        btnaltamateria.setText("Nueva Materia");
        btnaltamateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaltamateriaActionPerformed(evt);
            }
        });

        btnaltareticula.setText("Generar Reticula");
        btnaltareticula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaltareticulaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nuevo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnaltasemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnaltamateria, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnaltareticula))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(btnaltasemestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaltamateria, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnaltareticula)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpusuarioLayout = new javax.swing.GroupLayout(jpusuario);
        jpusuario.setLayout(jpusuarioLayout);
        jpusuarioLayout.setHorizontalGroup(
            jpusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpusuarioLayout.createSequentialGroup()
                .addGroup(jpusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpusuarioLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lbienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpusuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpusuarioLayout.setVerticalGroup(
            jpusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpusuarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtabla);

        btnnuevo.setText("Nuevo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Materia", "Semestre", "Reticula" }));

        jLabel1.setText("Busqueda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jctipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Materia", "Semestre", "Reticula" }));
        jctipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jctipoItemStateChanged(evt);
            }
        });
        jctipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jctipoActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtros");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jctipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jctipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnnuevo)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnuevo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaltamateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaltamateriaActionPerformed
        new vtnAMateria().setVisible(true);

    }//GEN-LAST:event_btnaltamateriaActionPerformed

    private void btnaltasemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaltasemestreActionPerformed
        new vtnAMateria().setVisible(true);
    }//GEN-LAST:event_btnaltasemestreActionPerformed

    private void jctipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jctipoItemStateChanged

        if (jctipo.getSelectedIndex() == 0) {
            btnnuevo.setText("Nuevo");
        } else {
            btnnuevo.setText("Nuevo " + jctipo.getSelectedItem());
        }

        //jtabla.setModel(modelo);
        switch (jctipo.getSelectedIndex()) {
            case 1:
                modelo.setRowCount(0);
                modelo.setColumnCount(0);
                modelo.addColumn("nombre");
                modelo.addColumn("profesor");
                modelo.addColumn("creditos");
                modelo.addColumn("observaciones");

                try {
                    String sql = "Select nombre,abreviatura,profesor,creditos FROM cat_materia";
                    ps = con.prepareStatement(sql);
                    rs = ps.executeQuery();

                    ResultSetMetaData rrsw = rs.getMetaData();
                    int cantcolumnas = rrsw.getColumnCount();

                    while (rs.next()) {

                        Object[] filas = new Object[cantcolumnas];

                        for (int i = 0; i < cantcolumnas; i++) {
                            System.out.println("entro filassss");
                            filas[i] = rs.getObject(i + 1);
                        }
                        modelo.addRow(filas);
                    }

                } catch (SQLException e) {
                    System.out.println(e.toString());
                }

                break;
            case 2:
                modelo.setRowCount(0);
                modelo.setColumnCount(0);
                modelo.addColumn("Estado");

                try {
                    String sql = "Select tipo FROM cat_tipo_aprovacion";
                    ps = con.prepareStatement(sql);
                    rs = ps.executeQuery();
                    ResultSetMetaData rrsw = rs.getMetaData();
                    int cantcolumnas = rrsw.getColumnCount();
                    while (rs.next()) {
                        Object[] filas = new Object[cantcolumnas];
                        for (int i = 0; i < cantcolumnas; i++) {
                            filas[i] = rs.getObject(i + 1);
                        }
                        modelo.addRow(filas);
                    }

                } catch (SQLException e) {
                    System.out.println(e.toString());
                }
                break;

            case 3:
                modelo.setRowCount(0);
                modelo.setColumnCount(0);
                modelo.addColumn("nombre");
                modelo.addColumn("profesor");
                modelo.addColumn("Parcial 1");
                modelo.addColumn("Parcial 2");
                modelo.addColumn("Ordinario");
                modelo.addColumn("Extra");
                modelo.addColumn("Titulo");
                modelo.addColumn("Estado");
                modelo.addColumn("Observaciones");
                jtabla.getColumnModel().getColumn(0).setPreferredWidth(200);
                jtabla.getColumnModel().getColumn(1).setPreferredWidth(100);
                jtabla.getColumnModel().getColumn(6).setPreferredWidth(50);
                jtabla.getColumnModel().getColumn(7).setPreferredWidth(50);
                try {
                    String sql = "Select nombre,profesor,parcial1,parcial2,ordinario,extra,titulo,estado,observaciones FROM ctrl_reticula \n"
                            + "                            inner join cat_materia 	on  (cat_materia.nombre = nombre)\n"
                            + "                            AND  (cat_materia.profesor = profesor)\n"
                            + "                            AND  (cat_materia.observaciones = observaciones)";
                    ps = con.prepareStatement(sql);
                    rs = ps.executeQuery();
                    ResultSetMetaData rrsw = rs.getMetaData();
                    int cantcolumnas = rrsw.getColumnCount();

                    while (rs.next()) {

                        Object[] filas = new Object[cantcolumnas];

                        for (int i = 0; i < cantcolumnas; i++) {
                            System.out.println("entro filassss");
                            filas[i] = rs.getObject(i + 1);
                        }
                        modelo.addRow(filas);
                    }

                } catch (SQLException e) {
                    System.out.println(e.toString());
                }
                break;
        }
        /*
        try {

            String sql = "Select codigo,nombre,precio,cantidad FROM producto";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rrsw = rs.getMetaData();
            int cantcolumnas = rrsw.getColumnCount();

            while (rs.next()) {

                Object[] filas = new Object[cantcolumnas];

                for (int i = 0; i < cantcolumnas; i++) {
                    System.out.println("entro filassss");
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException e) {
            System.out.println(e.toString());
        }
         */

    }//GEN-LAST:event_jctipoItemStateChanged

    private void btnaltareticulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaltareticulaActionPerformed
        new vtnAMateria().setVisible(true);
    }//GEN-LAST:event_btnaltareticulaActionPerformed

    private void jctipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jctipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jctipoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //jtabla.setModel(modelo);
        PreparedStatement ps = null;
        ResultSet rs;
        Connection con = Conexiones.conectar();
        modelo.setColumnCount(0);
        modelo.addColumn("Semestre");
        modelo.addColumn("Periodo");
        modelo.addColumn("Año");

        try {
            String sql = "Select numero,periodo,anio FROM crtl_semestre ";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rrsw = rs.getMetaData();
            int cantcolumnas = rrsw.getColumnCount();

            while (rs.next()) {

                Object[] filas = new Object[cantcolumnas];

                for (int i = 0; i < cantcolumnas; i++) {
                    System.out.println("entro filassss");
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException e) {
            System.out.println(e.toString());
        }

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaltamateria;
    private javax.swing.JButton btnaltareticula;
    private javax.swing.JButton btnaltasemestre;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jctipo;
    private javax.swing.JPanel jpusuario;
    private javax.swing.JTable jtabla;
    private javax.swing.JLabel lbienvenido;
    // End of variables declaration//GEN-END:variables
}
